spring:
    application:
        name: my-api-gateway-with-central-security
    config:
        import: 'configserver:http://localhost:8888'
    cloud:
        gateway:
            default-filters:
                - TokenRelay= 
            routes:
                - id: callme-service
                  uri:  http://localhost:3001
                  predicates:
                    - Path=/callme/**

                - id: caller-service
                  uri:  http://localhost:3002
                  predicates:
                    - Path=/caller/**
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8080/realms/demo/protocol/openid-connect/certs

            client:
                provider:
                    keycloak:
                        issuer-uri: http://localhost:8080/realms/demo
                registration:
                    spring-with-test-scope:
                        provider: keycloak
                        client-id: spring-with-test-scope
                        client-secret: IWLSnakHG8aNTWNaWuSj0a11UY4lzxd9
                        authorization-grant-type: authorization_code
                        scope: openid
           

server:
  port: '5000'

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'